### ISSUE TITLE
1.21鸡笼子没法抓自然生成的鸡

### ISSUE THREAD

**Issue by hseermc** [CrispyXYZ/GeneticChickengineering-CN-RC30-Extended#13]
鸡笼子只能抓鸡蛋砸出来的鸡和两只鸡喂种子繁殖的小鸡
[16:17:22 ERROR]: [GeneticChickengineering] Item "GCE_CHICKEN_NET" from GeneticChickengineering vBuild 8 (git a6cd374) has caused an Error!
[16:17:22 ERROR]: [GeneticChickengineering] You can report it here: https://github.com/CrispyXYZ/GeneticChickengineering-CN-RC30-Extended/issues
[16:17:22 ERROR]: [GeneticChickengineering] Could not pass "EntityInteractHandler" for ChickenNet - 'GCE_CHICKEN_NET' (GeneticChickengineering vBuild 8 (git a6cd374))
java.lang.IllegalArgumentException: Invalid UUID string: minecraft:random_spawn_bonus
        at java.base/java.util.UUID.fromString1(UUID.java:282) ~[?:?]
        at java.base/java.util.UUID.fromString(UUID.java:260) ~[?:?]
        at org.bukkit.attribute.AttributeModifier.getUniqueId(AttributeModifier.java:74) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at GeneticChickengineering-Build 8 (git a6cd374) (1).jar/space.kiichan.geneticchickengineering.adapter.MobAdapter.saveData(MobAdapter.java:184) ~[GeneticChickengineering-Build 8 (git a6cd374) (1).jar:?]
        at GeneticChickengineering-Build 8 (git a6cd374) (1).jar/space.kiichan.geneticchickengineering.adapter.AnimalsAdapter.saveData(AnimalsAdapter.java:40) ~[GeneticChickengineering-Build 8 (git a6cd374) (1).jar:?]
        at GeneticChickengineering-Build 8 (git a6cd374) (1).jar/space.kiichan.geneticchickengineering.chickens.PocketChicken.convert(PocketChicken.java:105) ~[GeneticChickengineering-Build 8 (git a6cd374) (1).jar:?]
        at GeneticChickengineering-Build 8 (git a6cd374) (1).jar/space.kiichan.geneticchickengineering.GeneticChickengineering.convert(GeneticChickengineering.java:189) ~[GeneticChickengineering-Build 8 (git a6cd374) (1).jar:?]
        at GeneticChickengineering-Build 8 (git a6cd374) (1).jar/space.kiichan.geneticchickengineering.items.ChickenNet.lambda$getItemHandler$0(ChickenNet.java:34) ~[GeneticChickengineering-Build 8 (git a6cd374) (1).jar:?]
        at Slimefun-14602eb-Insider.jar/io.github.thebusybiscuit.slimefun4.implementation.listeners.entity.EntityInteractionListener.lambda$onInteractEntity$0(EntityInteractionListener.java:51) ~[Slimefun-14602eb-Insider.jar:?]
        at Slimefun-14602eb-Insider.jar/io.github.thebusybiscuit.slimefun4.api.items.SlimefunItem.callItemHandler(SlimefunItem.java:1003) ~[Slimefun-14602eb-Insider.jar:?]
        at Slimefun-14602eb-Insider.jar/io.github.thebusybiscuit.slimefun4.implementation.listeners.entity.EntityInteractionListener.onInteractEntity(EntityInteractionListener.java:49) ~[Slimefun-14602eb-Insider.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor132.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:59) ~[leaves-1.21.jar:1.21-46-c19e742]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[leaves-1.21.jar:1.21-46-c19e742]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl$3.performInteraction(ServerGamePacketListenerImpl.java:2722) ~[leaves-1.21.jar:1.21-46-c19e742]
        at net.minecraft.server.network.ServerGamePacketListenerImpl$3.onInteraction(ServerGamePacketListenerImpl.java:2770) ~[leaves-1.21.jar:1.21-46-c19e742]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket$InteractionAction.dispatch(ServerboundInteractPacket.java:138) ~[leaves-1.21.jar:1.21-46-c19e742]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.dispatch(ServerboundInteractPacket.java:89) ~[leaves-1.21.jar:1.21-46-c19e742]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleInteract(ServerGamePacketListenerImpl.java:2711) ~[leaves-1.21.jar:1.21-46-c19e742]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:76) ~[leaves-1.21.jar:1.21-46-c19e742]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:14) ~[leaves-1.21.jar:1.21-46-c19e742]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:55) ~[leaves-1.21.jar:1.21-46-c19e742]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[leaves-1.21.jar:1.21-46-c19e742]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[leaves-1.21.jar:1.21-46-c19e742]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[leaves-1.21.jar:1.21-46-c19e742]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1536) ~[leaves-1.21.jar:1.21-46-c19e742]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:196) ~[leaves-1.21.jar:1.21-46-c19e742]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[leaves-1.21.jar:1.21-46-c19e742]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1513) ~[leaves-1.21.jar:1.21-46-c19e742]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1506) ~[leaves-1.21.jar:1.21-46-c19e742]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[leaves-1.21.jar:1.21-46-c19e742]
        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1465) ~[leaves-1.21.jar:1.21-46-c19e742]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1472) ~[leaves-1.21.jar:1.21-46-c19e742]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1317) ~[leaves-1.21.jar:1.21-46-c19e742]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:325) ~[leaves-1.21.jar:1.21-46-c19e742]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by CrispyXYZ** [comment]
已复现，正在修复

**Comment by CrispyXYZ** [comment]
已修复，可在[此处](https://builds.guizhanss.com/CrispyXYZ/GeneticChickengineering-CN-RC30-Extended/master/builds/9)下载新版本
